AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    ApiGatewayRestApi:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Name: "pc"
            Description: "Created by AWS Lambda"
            ApiKeySourceType: "HEADER"
            EndpointConfiguration: 
                Types: 
                  - "REGIONAL"

    LambdaFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            FunctionName: "preference-center2-PCDeployer-1CJS1TWFB1MYW"
            Handler: "deployer.resource_handler"
            Code: 
                S3Bucket: "prod-04-2014-tasks"
                S3Key: !Sub "/snapshots/${AWS::AccountId}/preference-center2-PCDeployer-1CJS1TWFB1MYW-7457af2c-42c8-465e-9246-77fb09db84fb"
                S3ObjectVersion: "xkEc7bcM2Vbk60LtrADrT3aXOIZd8rbx"
            MemorySize: 128
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/preference-center2-PCDeployerRole-47BZEKUA6KSN"
            Runtime: "python3.6"
            Timeout: 600
            TracingConfig: 
                Mode: "PassThrough"
            Layers: 
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:preference-center2:1"

    LambdaFunction2:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: "A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway."
            Environment: 
                Variables: 
                    "METADATA_TABLE": "preferenceCenterMetadata"
                    "CORS_DOMAIN": "*"
                    REGION: !Ref AWS::Region
            FunctionName: "preferenceCenter"
            Handler: "index.handler"
            Code: 
                S3Bucket: "prod-04-2014-tasks"
                S3Key: !Sub "/snapshots/${AWS::AccountId}/preferenceCenter-12c4e32c-08cf-4d5d-adbf-9a7030af12b5"
                S3ObjectVersion: "sthkaXb38bZ1AUfJN8LJOSDsLlyqwlti"
            MemorySize: 512
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/preferenceCenterLambda"
            Runtime: "nodejs12.x"
            Timeout: 10
            TracingConfig: 
                Mode: "PassThrough"

    CloudFrontDistribution:
        Type: "AWS::CloudFront::Distribution"
        Properties:
            DistributionConfig: 
                Origins: 
                  - 
                    ConnectionAttempts: 3
                    ConnectionTimeout: 10
                    DomainName: "davelem-scratchpad-preference-center.s3.amazonaws.com"
                    Id: "S3-davelem-scratchpad-preference-center"
                    OriginPath: ""
                    S3OriginConfig: 
                        OriginAccessIdentity: "origin-access-identity/cloudfront/E3MRF4MPT7GPWE"
                OriginGroups: 
                    Quantity: 0
                DefaultCacheBehavior: 
                    AllowedMethods: 
                      - "HEAD"
                      - "GET"
                    CachedMethods: 
                      - "HEAD"
                      - "GET"
                    Compress: false
                    DefaultTTL: 86400
                    ForwardedValues: 
                        Cookies: 
                            Forward: "none"
                        QueryString: false
                    MaxTTL: 31536000
                    MinTTL: 0
                    SmoothStreaming: false
                    TargetOriginId: "S3-davelem-scratchpad-preference-center"
                    ViewerProtocolPolicy: "redirect-to-https"
                Comment: ""
                PriceClass: "PriceClass_100"
                Enabled: true
                ViewerCertificate: 
                    CloudFrontDefaultCertificate: true
                    MinimumProtocolVersion: "TLSv1"
                Restrictions: 
                    GeoRestriction: 
                        RestrictionType: "none"
                HttpVersion: "http2"
                IPV6Enabled: true

    PinpointApp:
        Type: "AWS::Pinpoint::App"
        Properties:
            Name: "PreferenceCenter"

